version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-resume_db}
      POSTGRES_USER: ${POSTGRES_USER:-resume_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-resume_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: /entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
