name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: resume_user
          POSTGRES_DB: resume_db
          POSTGRES_PASSWORD: resume_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U resume_user -d resume_db" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgres://resume_user:resume_pass@localhost:5432/resume_db
      SECRET_KEY: ci-secret-key
      DEBUG: "True"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do pg_isready -h localhost -p 5432 && break || sleep 2; done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test --verbosity=2
